log_config_file = "src/bot/logging_info.ini"
post_replied_to_file = "data/posts_replied_to.txt"
responses_csv = "data/dialogues.csv"
trigger_file = "src/bot/trigger.json"
sub_json = "src/bot/subs.json"
praw_ini = "praw.ini"
env = "src/bot/.env"